# Generated by Django 5.0.1 on 2026-05-04 16:37

import os

from django.conf import settings
from django.db import migrations, models


def load_sql_views():
    sql_path = os.path.join(settings.BASE_DIR, 'POSTGRESQL_ANALYTICS_VIEWS.sql')
    with open(sql_path, 'r', encoding='utf-8') as sql_file:
        return sql_file.read()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleWithDates',
            fields=[
                ('schedule_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tprn', models.CharField(max_length=20)),
                ('sub_test_name', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=3)),
                ('scheduled_date', models.DateField()),
                ('scheduled_month', models.DateField()),
                ('scheduled_year', models.SmallIntegerField()),
                ('month_label', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=150, null=True)),
                ('is_confirmed', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Exam Schedule With Dates',
                'verbose_name_plural': 'Exam Schedules With Dates',
                'db_table': 'v_exam_schedule_with_dates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyActivityBreakdown',
            fields=[
                ('prn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('tprn', models.CharField(max_length=20)),
                ('sub_test_name', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=3)),
                ('month_label', models.CharField(max_length=20)),
                ('exam_month', models.DateField()),
                ('attempts_in_month', models.IntegerField()),
                ('marks_in_month', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Monthly Activity Breakdown',
                'verbose_name_plural': 'Monthly Activity Breakdowns',
                'db_table': 'v_monthly_activity_breakdown',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCategoryScore',
            fields=[
                ('prn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('centre_code', models.CharField(max_length=3)),
                ('course_code', models.CharField(max_length=2)),
                ('enroll_year', models.SmallIntegerField()),
                ('batch_month', models.CharField(max_length=2)),
                ('category_code', models.CharField(max_length=3)),
                ('category_name', models.CharField(max_length=100)),
                ('original_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('scaled_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scaled_score', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name': 'Student Category Score',
                'verbose_name_plural': 'Student Category Scores',
                'db_table': 'v_student_category_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGrandTotal',
            fields=[
                ('prn', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('centre_code', models.CharField(max_length=3)),
                ('course_code', models.CharField(max_length=2)),
                ('enroll_year', models.SmallIntegerField()),
                ('batch_month', models.CharField(max_length=2)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(max_length=2, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Student Grand Total',
                'verbose_name_plural': 'Student Grand Totals',
                'db_table': 'v_student_grand_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentScoresByDate',
            fields=[
                ('score_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prn', models.CharField(max_length=12)),
                ('full_name', models.CharField(max_length=150)),
                ('tprn', models.CharField(max_length=20)),
                ('sub_test_name', models.CharField(max_length=100)),
                ('category_code', models.CharField(max_length=3)),
                ('exam_date', models.DateField()),
                ('exam_month', models.DateField()),
                ('exam_year', models.SmallIntegerField()),
                ('month_label', models.CharField(max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('is_absent', models.BooleanField()),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'verbose_name': 'Student Scores By Date',
                'verbose_name_plural': 'Student Scores By Date',
                'db_table': 'v_student_scores_by_date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text='User who performed the action')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View')], help_text='Action performed (CREATE, UPDATE, DELETE, VIEW)', max_length=50)),
                ('model_name', models.CharField(help_text="Model name (e.g., 'Student', 'StudentTestScore')", max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object modified', max_length=100, null=True)),
                ('changes', models.JSONField(blank=True, help_text='JSON of field changes (old_value -> new_value)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of requester', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of action')),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'managed': True,
                'indexes': [models.Index(fields=['user_id'], name='audit_log_user_id_4dac76_idx'), models.Index(fields=['model_name'], name='audit_log_model_n_d0c22c_idx'), models.Index(fields=['created_at'], name='audit_log_created_5a7975_idx')],
            },
        ),
        migrations.RunSQL(sql=load_sql_views(), reverse_sql=migrations.RunSQL.noop),
    ]
