# Generated by Django 5.0.1 on 2026-05-04 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreCourseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre_code', models.CharField(help_text="Centre code (e.g., '001')", max_length=3)),
                ('centre_name', models.CharField(help_text='Centre name', max_length=100)),
                ('course_code', models.CharField(help_text="Course code (e.g., '28' for BCA)", max_length=2)),
                ('course_name', models.CharField(help_text='Course name', max_length=100)),
                ('max_students', models.SmallIntegerField(help_text='Maximum students in batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('enroll_year', models.SmallIntegerField(help_text='Year of enrollment (e.g., 2023)')),
                ('batch_month', models.CharField(choices=[('02', 'February'), ('08', 'August')], help_text='Batch month (Feb or Aug)', max_length=2)),
                ('batch_label', models.CharField(editable=False, help_text="Generated field: e.g., 'F23' for Feb 2023", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centre Course Batch',
                'verbose_name_plural': 'Centre Course Batches',
                'db_table': 'centres_courses_batches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text='Scheduled date of exam')),
                ('scheduled_month', models.DateField(editable=False, help_text='Generated: First day of scheduled month')),
                ('venue', models.CharField(blank=True, help_text='Exam venue', max_length=150, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('is_confirmed', models.BooleanField(default=False, help_text='Is schedule confirmed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'db_table': 'exam_schedule',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('grade', models.CharField(help_text='Grade (A+, A, B+, B, C+, C, F)', max_length=2, primary_key=True, serialize=False)),
                ('min_marks', models.DecimalField(decimal_places=2, help_text='Minimum marks for this grade', max_digits=7)),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this grade', max_digits=7)),
                ('description', models.CharField(help_text='Grade description', max_length=50)),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'db_table': 'grade_scale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('category_code', models.CharField(help_text="Category code (e.g., 'MSE', 'ESE')", max_length=3, primary_key=True, serialize=False)),
                ('category_name', models.CharField(help_text='Category name', max_length=100)),
                ('original_total', models.DecimalField(decimal_places=2, help_text='Original max marks for category', max_digits=8)),
                ('scaled_total', models.DecimalField(decimal_places=2, help_text='Scaled max marks (normalized to 1500 overall)', max_digits=8)),
                ('pct_of_1500', models.DecimalField(decimal_places=4, editable=False, help_text='Generated: Percentage of 1500 total', max_digits=6)),
                ('description', models.TextField(blank=True, help_text='Category description', null=True)),
            ],
            options={
                'verbose_name': 'Main Category',
                'verbose_name_plural': 'Main Categories',
                'db_table': 'main_categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('prn', models.CharField(help_text='Permanent Registration Number (12 digits)', max_length=12, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Full name of student', max_length=150)),
                ('centre_code', models.CharField(help_text='Centre code (links to CentreCourseBatch)', max_length=3)),
                ('course_code', models.CharField(help_text='Course code (links to CentreCourseBatch)', max_length=2)),
                ('enroll_year', models.SmallIntegerField(editable=False, help_text='Generated: Year of enrollment')),
                ('batch_month', models.CharField(editable=False, help_text='Generated: Batch month (02 or 08)', max_length=2)),
                ('serial_no', models.SmallIntegerField(editable=False, help_text='Generated: Serial number in batch')),
                ('is_active', models.BooleanField(default=True, help_text='Is student active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTestScore',
            fields=[
                ('score_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Actual score obtained (null if absent)', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_absent', models.BooleanField(default=False, help_text='Was student absent?')),
                ('exam_date', models.DateField(help_text='Date of exam')),
                ('exam_month', models.DateField(editable=False, help_text='Generated: First day of exam month')),
                ('exam_year', models.SmallIntegerField(editable=False, help_text='Generated: Year of exam')),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Test Score',
                'verbose_name_plural': 'Student Test Scores',
                'db_table': 'student_test_scores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubTest',
            fields=[
                ('tprn', models.CharField(help_text='Test Permanent Registration Number (unique identifier)', max_length=20, primary_key=True, serialize=False)),
                ('sub_test_name', models.CharField(help_text='Name of the test', max_length=100)),
                ('type_code', models.CharField(help_text="Test type code (e.g., 'TEST', 'ASGN')", max_length=5)),
                ('centre_code', models.CharField(help_text='Centre code', max_length=3)),
                ('course_code', models.CharField(help_text='Course code', max_length=2)),
                ('enroll_year', models.SmallIntegerField(help_text='Enrollment year')),
                ('batch_month', models.CharField(choices=[('02', 'February'), ('08', 'August')], help_text='Batch month', max_length=2)),
                ('batch_label', models.CharField(help_text="Batch label (e.g., 'F23')", max_length=10)),
                ('max_marks', models.DecimalField(decimal_places=2, help_text='Maximum marks for this test', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SubTest',
                'verbose_name_plural': 'SubTests',
                'db_table': 'sub_tests',
                'managed': True,
            },
        ),
    ]
