# Generated by Django 5.2.1 on 2026-05-08 05:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_name', models.CharField(help_text="Batch name (e.g., 'Feb/24', 'Aug/24')", max_length=10, primary_key=True, serialize=False)),
                ('batch_month', models.CharField(choices=[('02', 'February'), ('08', 'August')], help_text='Batch month code (02 or 08)', max_length=2)),
                ('batch_year', models.SmallIntegerField(help_text='Year (e.g., 2024)')),
                ('is_active', models.BooleanField(default=True, help_text='Is this batch active?')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'db_table': 'batches',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('centre_code', models.CharField(help_text="Centre code (e.g., '001', '002')", max_length=3, primary_key=True, serialize=False)),
                ('centre_name', models.CharField(help_text="Centre name (e.g., 'Mumbai', 'Delhi')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this centre active?')),
            ],
            options={
                'verbose_name': 'Centre',
                'verbose_name_plural': 'Centres',
                'db_table': 'centres',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(help_text="Course code (e.g., '28' for BCA, '14' for MCA)", max_length=2, primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text="Course name (e.g., 'Bachelor of Computer Applications')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this course active?')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('prn', models.CharField(help_text='Permanent Registration Number', max_length=20, primary_key=True, serialize=False)),
                ('student_full_name', models.CharField(help_text='Full name of student', max_length=150)),
                ('centre_code', models.CharField(db_column='centre_code_denorm', editable=False, help_text='Derived: Centre code (auto-populated from centre)', max_length=3)),
                ('centre_name', models.CharField(editable=False, help_text='Derived: Centre name (auto-populated from centre)', max_length=100)),
                ('course_code', models.CharField(db_column='course_code_denorm', editable=False, help_text='Derived: Course code (auto-populated from course)', max_length=2)),
                ('course_name', models.CharField(editable=False, help_text='Derived: Course name (auto-populated from course)', max_length=100)),
                ('batch_name', models.CharField(db_column='batch_name_denorm', editable=False, help_text='Derived: Batch name (auto-populated from batch)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is student active? (soft delete via this flag)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this student was created', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this student was last updated', null=True)),
            ],
            options={
                'verbose_name': 'Student Master',
                'verbose_name_plural': 'Student Masters',
                'db_table': 'student_master',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='centrecoursebatch',
            options={'managed': False, 'verbose_name': 'Centre Course Batch (Legacy)', 'verbose_name_plural': 'Centre Course Batches (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False, 'verbose_name': 'Student (Legacy)', 'verbose_name_plural': 'Students (Legacy)'},
        ),
        migrations.RenameField(
            model_name='subtest',
            old_name='sub_test_name',
            new_name='subtest_name',
        ),

        migrations.RemoveField(
            model_name='maincategory',
            name='original_total',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='pct_of_1500',
        ),
        migrations.RemoveField(
            model_name='maincategory',
            name='scaled_total',
        ),
        migrations.AddField(
            model_name='examschedule',
            name='tprn',
            field=models.ForeignKey(db_column='tprn', default='APT-001', help_text='Reference to test', on_delete=django.db.models.deletion.PROTECT, to='assessments.subtest'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='examschedule',
            unique_together={('tprn', 'scheduled_date')},
        ),
        migrations.AddField(
            model_name='maincategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this category was created', null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this category active? (soft delete via this flag)'),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='max_marks_per_subtest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max marks per subtest (reference only, NOT connected to other tables)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='no_of_subtests',
            field=models.SmallIntegerField(default=1, help_text='Maximum number of subtests allowed in this category', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='maincategory',
            name='scaled_marks',
            field=models.DecimalField(decimal_places=2, default='001', help_text='Scaled marks after all subtests are aggregated', max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this category was last updated', null=True),
        ),
        migrations.AddField(
            model_name='studenttestscore',
            name='batch_name',
            field=models.CharField(blank=True, help_text='Batch name (denormalized for reporting)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studenttestscore',
            name='category_code',
            field=models.CharField(blank=True, help_text='Category code (denormalized for reporting)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='studenttestscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this score was created', null=True),
        ),
        migrations.AddField(
            model_name='studenttestscore',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this score record active? (soft delete via this flag)'),
        ),
        migrations.AddField(
            model_name='studenttestscore',
            name='subtest_name',
            field=models.CharField(blank=True, help_text='Subtest name (denormalized for reporting)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttestscore',
            name='tprn',
            field=models.ForeignKey(db_column='tprn', default='Feb/24', help_text='Reference to test', on_delete=django.db.models.deletion.PROTECT, to='assessments.subtest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtest',
            name='category_code',
            field=models.ForeignKey(db_column='category_code', default='001', help_text='Assessment category', on_delete=django.db.models.deletion.PROTECT, to='assessments.maincategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtest',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this subtest active? (soft delete via this flag)'),
        ),
        migrations.AddField(
            model_name='subtest',
            name='test_date',
            field=models.DateField(blank=True, help_text='Date of the test (can be filled later)', null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='category_code',
            field=models.CharField(help_text="Category code (e.g., 'MSE', 'ESE', 'APT')", max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='category_name',
            field=models.CharField(help_text="Category name (e.g., 'Mid Semester Exam')", max_length=100),
        ),
        migrations.AlterField(
            model_name='studenttestscore',
            name='exam_date',
            field=models.DateField(blank=True, help_text='Date of exam (can be filled later)', null=True),
        ),
        migrations.AlterField(
            model_name='studenttestscore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this score was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this subtest was created', null=True),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='tprn',
            field=models.CharField(help_text="Test Permanent Registration Number (CATEGORY_CODE-SEQ, e.g., 'MSE-001')", max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this subtest was last updated', null=True),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['tprn'], name='exam_schedu_tprn_0f4835_idx'),
        ),
        migrations.AddIndex(
            model_name='examschedule',
            index=models.Index(fields=['scheduled_date'], name='exam_schedu_schedul_af2c04_idx'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['category_code'], name='main_catego_categor_e52526_idx'),
        ),
        migrations.AddIndex(
            model_name='maincategory',
            index=models.Index(fields=['is_active'], name='main_catego_is_acti_c96d66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('batch_month', 'batch_year')},
        ),
        migrations.AddField(
            model_name='subtest',
            name='batch_name',
            field=models.ForeignKey(db_column='batch_name', default='Feb/24', help_text="Batch (e.g., 'Feb/24')", on_delete=django.db.models.deletion.PROTECT, to='assessments.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtest',
            name='centre_code',
            field=models.ForeignKey(db_column='centre_code', help_text='Centre code', on_delete=django.db.models.deletion.PROTECT, to='assessments.centre'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='course_code',
            field=models.ForeignKey(db_column='course_code', help_text='Course code', on_delete=django.db.models.deletion.PROTECT, to='assessments.course'),
        ),
        migrations.AlterUniqueTogether(
            name='subtest',
            unique_together={('tprn', 'centre_code', 'course_code', 'batch_name')},
        ),
        migrations.AddIndex(
            model_name='subtest',
            index=models.Index(fields=['category_code', 'is_active'], name='sub_tests_categor_8f993f_idx'),
        ),
        migrations.AddIndex(
            model_name='subtest',
            index=models.Index(fields=['centre_code', 'course_code', 'batch_name'], name='sub_tests_centre__103131_idx'),
        ),
        migrations.AddIndex(
            model_name='subtest',
            index=models.Index(fields=['tprn', 'is_active'], name='sub_tests_tprn_73d6fa_idx'),
        ),
        migrations.AddField(
            model_name='studentmaster',
            name='batch',
            field=models.ForeignKey(help_text="Batch (e.g., 'Feb/24')", on_delete=django.db.models.deletion.PROTECT, to='assessments.batch'),
        ),
        migrations.AddField(
            model_name='studentmaster',
            name='centre',
            field=models.ForeignKey(help_text='Centre', on_delete=django.db.models.deletion.PROTECT, to='assessments.centre'),
        ),
        migrations.AddField(
            model_name='studentmaster',
            name='course',
            field=models.ForeignKey(help_text='Course', on_delete=django.db.models.deletion.PROTECT, to='assessments.course'),
        ),
        migrations.AddField(
            model_name='studenttestscore',
            name='prn',
            field=models.ForeignKey(db_column='prn', default='28', help_text='Reference to student', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studenttestscore',
            unique_together={('tprn', 'prn')},
        ),
        migrations.AddIndex(
            model_name='studenttestscore',
            index=models.Index(fields=['prn', 'is_active'], name='student_tes_prn_b5aa3a_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestscore',
            index=models.Index(fields=['tprn', 'is_active'], name='student_tes_tprn_2a7f18_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestscore',
            index=models.Index(fields=['exam_date'], name='student_tes_exam_da_c72efa_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttestscore',
            index=models.Index(fields=['is_active'], name='student_tes_is_acti_bb17e9_idx'),
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examschedule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subtest',
            name='batch_label',
        ),
        migrations.RemoveField(
            model_name='subtest',
            name='batch_month',
        ),
        migrations.RemoveField(
            model_name='subtest',
            name='enroll_year',
        ),
        migrations.RemoveField(
            model_name='subtest',
            name='type_code',
        ),
        migrations.AddIndex(
            model_name='studentmaster',
            index=models.Index(fields=['prn', 'is_active'], name='student_mas_prn_0a8615_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaster',
            index=models.Index(fields=['centre_code'], name='student_mas_centre__f8b1c4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaster',
            index=models.Index(fields=['course_code'], name='student_mas_course__175c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaster',
            index=models.Index(fields=['batch_name'], name='student_mas_batch_n_8f9141_idx'),
        ),
        migrations.RemoveField(
            model_name='studenttestscore',
            name='entered_at',
        ),
        migrations.RemoveField(
            model_name='studenttestscore',
            name='exam_month',
        ),
        migrations.RemoveField(
            model_name='studenttestscore',
            name='exam_year',
        ),
    ]
