# Generated by Django 5.2.1 on 2026-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_subtest_subtest_name_categorycoursemapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this mapping was created', null=True),
        ),
        migrations.AddField(
            model_name='testmapping',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this mapping was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this mapping active?'),
        ),
    ]
