# Generated by Django 5.2.1 on 2026-05-11 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_testmapping_created_at_testmapping_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreap',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scoreas',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scorecc',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scoregr',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scorein',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scoremt',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scorena',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scorepq',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scoreps',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scoresx',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
        migrations.AlterField(
            model_name='scoreta',
            name='prn',
            field=models.ForeignKey(db_column='prn', on_delete=django.db.models.deletion.PROTECT, to='assessments.studentmaster'),
        ),
    ]
