# Generated by Django 5.2.1 on 2026-05-14 05:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_reconcile_score_model_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoreap',
            options={'managed': False, 'verbose_name': 'Scores - Aptitude'},
        ),
        migrations.AlterModelOptions(
            name='scoreas',
            options={'managed': False, 'verbose_name': 'Scores - Advanced Systems'},
        ),
        migrations.AlterModelOptions(
            name='scorecc',
            options={'managed': False, 'verbose_name': 'Scores - C/C++ Programming'},
        ),
        migrations.AlterModelOptions(
            name='scoregr',
            options={'managed': False, 'verbose_name': 'Scores - Graphics'},
        ),
        migrations.AlterModelOptions(
            name='scoreia',
            options={'managed': False, 'verbose_name': 'Scores - IA / Module'},
        ),
        migrations.AlterModelOptions(
            name='scorein',
            options={'managed': False, 'verbose_name': 'Scores - Internet'},
        ),
        migrations.AlterModelOptions(
            name='scorena',
            options={'managed': False, 'verbose_name': 'Scores - Networking'},
        ),
        migrations.AlterModelOptions(
            name='scorepq',
            options={'managed': False, 'verbose_name': 'Scores - Programming (Advanced)'},
        ),
        migrations.AlterModelOptions(
            name='scoreps',
            options={'managed': False, 'verbose_name': 'Scores - Programming (Systems)'},
        ),
        migrations.AlterModelOptions(
            name='scoresx',
            options={'managed': False, 'verbose_name': 'Scores - Software Extras'},
        ),
        migrations.AlterModelOptions(
            name='scoreta',
            options={'managed': False, 'verbose_name': 'Scores - Technical Aptitude'},
        ),
        migrations.RemoveIndex(
            model_name='studentmaster',
            name='student_mas_centre__f8b1c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentmaster',
            name='student_mas_course__175c6b_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentmaster',
            name='student_mas_batch_n_8f9141_idx',
        ),
        migrations.RenameIndex(
            model_name='testmapping',
            new_name='test_mappin_batch_n_90ba9f_idx',
            old_name='assessments_tm_batch_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='testmapping',
            new_name='test_mappin_is_acti_be4c71_idx',
            old_name='assessments_tm_is_active_idx',
        ),
        migrations.AlterField(
            model_name='categorycoursemapping',
            name='category',
            field=models.ForeignKey(db_column='category_code', on_delete=django.db.models.deletion.CASCADE, to='assessments.maincategory'),
        ),
        migrations.AlterField(
            model_name='categorycoursemapping',
            name='course',
            field=models.ForeignKey(db_column='course_code', on_delete=django.db.models.deletion.CASCADE, to='assessments.course'),
        ),
        migrations.AlterField(
            model_name='studentmaster',
            name='centre',
            field=models.ForeignKey(help_text='Centre (stored for data integrity; not used in filtering)', on_delete=django.db.models.deletion.PROTECT, to='assessments.centre'),
        ),
        migrations.AlterField(
            model_name='subtest',
            name='subtest_name',
            field=models.CharField(help_text='Name of the test', max_length=100),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='batch_name',
            field=models.ForeignKey(db_column='batch_name', help_text="Batch (e.g., 'Feb/24')", on_delete=django.db.models.deletion.PROTECT, to='assessments.batch'),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='category_code',
            field=models.ForeignKey(db_column='category_code', help_text='Assessment category', on_delete=django.db.models.deletion.PROTECT, to='assessments.maincategory'),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='column_slot',
            field=models.CharField(help_text="Excel column slot reference (e.g., 'test_01')", max_length=50),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this mapping active?'),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='logical_name',
            field=models.CharField(help_text="Logical name for the test (e.g., 'Aptitude 1')", max_length=100),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='max_marks',
            field=models.DecimalField(decimal_places=2, help_text='Maximum marks for this logical test', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='testmapping',
            name='sequence',
            field=models.SmallIntegerField(default=1, help_text='Sequence order in UI/Reports'),
        ),
        migrations.AddIndex(
            model_name='studentmaster',
            index=models.Index(fields=['centre_id'], name='student_mas_centre__29c921_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaster',
            index=models.Index(fields=['course_id'], name='student_mas_course__3e774e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmaster',
            index=models.Index(fields=['batch_id'], name='student_mas_batch_i_93f00e_idx'),
        ),
    ]
